#!/usr/bin/env python
"""Generate packed ethylene carbonate boxes for the density example."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


HERE = Path(__file__).resolve().parent
ATOM_NAMES = ("O00", "C01", "O02", "C03", "C04", "O05", "H06", "H07", "H08", "H09")
ELEMENTS = ("O", "C", "O", "C", "C", "O", "H", "H", "H", "H")

# Angstrom coordinates for one EC molecule, matching ec_init.pdb atom order.
EC_COORDS = (
    (0.000, 1.200, 0.000),
    (0.000, 0.000, 0.000),
    (1.100, -0.700, 0.000),
    (0.700, -2.100, 0.000),
    (-0.700, -2.100, 0.000),
    (-1.100, -0.700, 0.000),
    (1.200, -2.500, 0.800),
    (1.200, -2.500, -0.800),
    (-1.200, -2.500, 0.800),
    (-1.200, -2.500, -0.800),
)

EC_MASS_DA = 3 * 12.0107 + 4 * 1.00784 + 3 * 15.999
DA_PER_NM3_TO_G_PER_ML = 0.00166053906660


def box_length_angstrom(molecules: int, density_g_ml: float) -> float:
    volume_nm3 = molecules * EC_MASS_DA * DA_PER_NM3_TO_G_PER_ML / density_g_ml
    return (volume_nm3 ** (1.0 / 3.0)) * 10.0


def write_monomer(path: Path) -> None:
    with path.open("w") as handle:
        handle.write("REMARK   EC monomer for packmol\n")
        for index, (name, element, coord) in enumerate(zip(ATOM_NAMES, ELEMENTS, EC_COORDS), start=1):
            x, y, z = coord
            handle.write(
                f"ATOM  {index:5d} {name:<4s} ECA A   1    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           {element:>2s}\n"
            )
        handle.write("END\n")


def write_packmol_input(path: Path, monomer: Path, raw_output: Path, molecules: int, box_length: float, seed: int) -> None:
    contents = f"""tolerance 2.0
filetype pdb
output {raw_output}
pbc {box_length:.6f} {box_length:.6f} {box_length:.6f}
seed {seed}

structure {monomer}
  number {molecules}
  resnumbers 2
  inside box 0.0 0.0 0.0 {box_length:.6f} {box_length:.6f} {box_length:.6f}
end structure
"""
    path.write_text(contents)


def write_boxed_pdb(raw_output: Path, final_output: Path, box_length: float) -> None:
    cryst1 = f"CRYST1{box_length:9.3f}{box_length:9.3f}{box_length:9.3f}  90.00  90.00  90.00 P 1           1\n"
    lines = [line for line in raw_output.read_text().splitlines() if not line.startswith(("REMARK", "CRYST1"))]
    with final_output.open("w") as handle:
        handle.write("REMARK   EC liquid box generated by prepare_pdb.py\n")
        handle.write(cryst1)
        for line in lines:
            handle.write(line.rstrip() + "\n")


def find_packmol() -> str | None:
    packmol = shutil.which("packmol")
    if packmol is not None:
        return packmol

    # Conda installs packmol in the base prefix even when this script runs from
    # a project-specific env such as .../miniconda3/envs/phyneo/bin/python.
    executable = Path(sys.executable).resolve()
    for parent in executable.parents:
        candidate = parent / "bin" / "packmol"
        if candidate.exists() and candidate.is_file():
            return str(candidate)
    return None


def generate_box(output: Path, molecules: int, density_g_ml: float, seed: int) -> float:
    packmol = find_packmol()
    if packmol is None:
        raise RuntimeError("packmol is required to generate packed EC boxes")

    output = output.resolve()
    box_length = box_length_angstrom(molecules, density_g_ml)
    with tempfile.TemporaryDirectory(prefix="ec_packmol_") as tmp:
        tmpdir = Path(tmp)
        monomer = tmpdir / "ec_monomer.pdb"
        raw_output = tmpdir / "ec_packmol_raw.pdb"
        packmol_input = tmpdir / "pack_ec.inp"
        write_monomer(monomer)
        write_packmol_input(packmol_input, monomer, raw_output, molecules, box_length, seed)
        subprocess.run([packmol, "-i", str(packmol_input)], check=True, cwd=tmpdir)
        write_boxed_pdb(raw_output, output, box_length)
    return box_length


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=HERE / "ec_liquid_216.pdb")
    parser.add_argument("--molecules", type=int, default=216)
    parser.add_argument("--density", type=float, default=1.321, help="Target density in g/mL")
    parser.add_argument("--seed", type=int, default=2026)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    box_length = generate_box(args.output, args.molecules, args.density, args.seed)
    print(f"Wrote {args.output}")
    print(f"Molecules: {args.molecules}")
    print(f"Target density: {args.density:.3f} g/mL")
    print(f"Box length: {box_length:.3f} A")


if __name__ == "__main__":
    main()
